# -*- coding: utf-8 -*-
"""CarolGarcia_PGY1121SECCION006V

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1npQ7xu14Os6IA-MxahN2AY-VvfqZuPWO
"""

lotes = [
    [" ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " "]
]

detalles_lotes = [
    {"numero": 1, "tamaño": "500 m2", "precio": "$100,000"},
    {"numero": 2, "tamaño": "600 m2", "precio": "$120,000"},
    {"numero": 3, "tamaño": "400 m2", "precio": "$80,000"},
    {"numero": 4, "tamaño": "550 m2", "precio": "$110,000"},
    {"numero": 5, "tamaño": "450 m2", "precio": "$90,000"}
]

clientes = []

def mostrar_disponibilidad_lotes():
    print("Lotes Disponibles:")
    for fila in lotes:
        for lote in fila:
            print("[{}]".format(lote), end=" ")
        print()

def seleccionar_lote():
    rut = input("Ingrese su RUT: ")
    nombre = input("Ingrese su nombre completo: ")
    telefono = input("Ingrese su teléfono: ")
    email = input("Ingrese su email: ")
    fila = int(input("Ingrese la fila del lote: "))
    columna = int(input("Ingrese la columna del lote: "))

    if fila < 1 or fila > len(lotes) or columna < 1 or columna > len(lotes[0]):
        print("Coordenadas inválidas. Por favor, ingrese coordenadas válidas.")
        return

    if lotes[fila - 1][columna - 1] != " ":
        print("El lote seleccionado no está disponible. Por favor, elija otro lote.")
        return

    lotes[fila - 1][columna - 1] = "X"
    clientes.append({"RUT": rut, "nombre": nombre, "telefono": telefono, "email": email, "lote": (fila, columna)})

    print("¡Felicidades! Ha seleccionado el lote", (fila, columna), "exitosamente.")

def ver_detalles_lote():
    if len(clientes) == 0:
        print("No hay lotes seleccionados por clientes.")
        return

    rut = input("Ingrese su RUT: ")
    for cliente in clientes:
        if cliente["RUT"] == rut:
            lote = cliente["lote"]
            numero_lote = (lote[0] - 1) * len(lotes[0]) + lote[1]
            detalles = detalles_lotes[numero_lote - 1]
            print("Detalles del lote seleccionado:")
            print("Número de lote:", detalles["numero"])
            print("Tamaño del terreno:", detalles["tamaño"])
            print("Precio:", detalles["precio"])
            return

    print("No se encontró un lote seleccionado con el RUT ingresado.")

def ver_clientes():
    if len(clientes) == 0:
        print("No hay clientes registrados.")
        return

    print("Clientes que han comprado un lote:")
    for cliente in clientes:
        print("RUT:", cliente["RUT"])
        print("Nombre:", cliente["nombre"])
        print("Teléfono:", cliente["telefono"])
        print("Email:", cliente["email"])
        print("Lote seleccionado:", cliente["lote"])
        print()

def menu_interactivo():
    while True:
        print("-------- Menú --------")
        print("1. Ver disponibilidad de lotes")
        print("2. Seleccionar un lote")
        print("3. Ver detalles del lote seleccionado")
        print("4. Ver clientes")
        print("5. Salir")
        opcion = input("Seleccione una opción (1-5): ")

        if opcion == "1":
            mostrar_disponibilidad_lotes()
        elif opcion == "2":
            seleccionar_lote()
        elif opcion == "3":
            ver_detalles_lote()
        elif opcion == "4":
            ver_clientes()
        elif opcion == "5":
            print("¡Gracias por utilizar nuestro sistema!")
            break
        else:
            print("Opción inválida. Por favor, seleccione una opción válida.")

menu_interactivo()